config/routes.rb
Rails.application.routes.draw do
  #get 'profiles/show'
  devise_for :users

  resources :restaurants do
    resources :dishes, only: [:create]
    resources :orders, only: [:index]
    get "/dashboard", to: "restaurants#dashboard"
    get "/index_today", to: "orders#index_today"
    get "/index_owner", to: "dishes#index_owner"
  end

  resources :dishes, only: [:index, :edit, :update, :destroy] do
    resources :orders, only: [:create, :index]


  end
  resources :profiles, only: [:show]
  resources :orders, only: [:show, :update]
  resources :chatrooms, only: :show do
    resources :messages, only: :create
  end

  patch ":id/claim", to: "orders#claim", as: :claim
  root to: 'pages#home'
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer row">
  <div class="footer-links">
    <a href="https://github.com/fematarazzo/sobrou_app"><i class="fab fa-github"></i></a>
  </div>
  <div class="footer-copyright">
    Mude seu consumo.
    <%= image_tag "logo_sobrou.png", alt: "Sobrou App", height: 60, width: 100%>
  </div>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar fixed-top navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "sobrou.png", alt: "Sobrou App"%>
    <% end %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <% if user_signed_in? %>
          <% if current_user.owner? %>
            <li class="nav-item">
              <%= link_to "Gerenciar meus restaurantes", restaurants_path, class: "nav-link" %>
            </li>
          <% end %>
          <li class="nav-item">
              <%= link_to "Meu Perfil", profile_path(current_user), class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "nav-link" %>
            </li>
          <%= cl_image_tag current_user.photo.key, class: "avatar", 'aria-haspopup': true, 'aria-expanded': false %>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Cadastre aqui", new_user_registration_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>