config/routes.rb
Rails.application.routes.draw do
  #get 'profiles/show'
  devise_for :users

  resources :restaurants do
    resources :dishes, only: [:create]
    resources :orders, only: [:index]
    get "/dashboard", to: "restaurants#dashboard"
    get "/index_today", to: "orders#index_today"
    get "/index_owner", to: "dishes#index_owner"
  end

  resources :dishes, only: [:index, :edit, :update, :destroy] do
    resources :orders, only: [:create, :index]


  end
  resources :profiles, only: [:show]
  resources :orders, only: [:show, :update]
  resources :chatrooms, only: :show do
    resources :messages, only: :create
  end

  patch ":id/claim", to: "orders#claim", as: :claim
  root to: 'pages#home'
end

app/models/dish.rb
class Dish < ApplicationRecord
  belongs_to :restaurant
  has_many :orders, dependent: :destroy
  validates :name, :price, :description, :quantity, presence: true
  has_one_attached :photo
end

app/controllers/dishes_controller.rb
class DishesController < ApplicationController
  before_action :set_dish, only: %i[show edit update destroy]
  # For authorizing users to navigate through some pages
  skip_before_action :authenticate_user!, only: [:index, :show]
  skip_after_action :verify_authorized, only: [:index_owner]

  def index
    skip_policy_scope
    # Checking the search bar params
    if params[:search][:address].blank? && params[:search][:category] == [""]
      @restaurants = policy_scope(Restaurant)
    elsif !params[:search][:address].blank? && params[:search][:category] == [""]
      @restaurants = Restaurant.near(params[:search][:address], 5)
    elsif params[:search][:address].blank? && params[:search][:category].size > 1
      @restaurants = Restaurant.where(category: params[:search][:category] - [""])
    elsif !params[:search][:address].blank? && params[:search][:category].nil?
      @restaurants = Restaurant.near(params[:search][:address], 5)
    else
      @restaurants = Restaurant.near(params[:search][:address], 5).where(category: params[:search][:category] - [""])
    end
    # For displaying which dishes
    @dishes = []
    @restaurants.each do |restaurant|
      restaurant.dishes.each { |dish| @dishes << dish }
    end
    @order = Order.new
  end

  def index_owner
    # Only for restaurant owner
    @restaurant = Restaurant.find(params[:restaurant_id])
    @dishes = policy_scope(Dish).select { |dish| @restaurant == dish.restaurant }
  end

  def create
    @dish = Dish.new(dish_params)
    @restaurant = Restaurant.find(params[:restaurant_id])
    @dish.restaurant = @restaurant
    authorize @dish
    if @dish.save
      redirect_to restaurant_index_owner_path(@restaurant)
    else
      redirect_to restaurant_dashboard_path(@restaurant)
    end
  end

  def edit
    @restaurant = @dish.restaurant
  end

  def update
    @dish.update(dish_params)
    if current_user.owner?
      redirect_to restaurant_index_owner_path(@dish.restaurant)
    else
      redirect_to profile_path(current_user)
    end
  end

  def destroy
    @dish.destroy
    redirect_to restaurant_index_owner_path(@dish.restaurant)
  end

  private

  def set_dish
    @dish = Dish.find(params[:id])
    @dish = Dish.includes(:restaurant).find(params[:id])
    authorize @dish
  end

  def dish_params
    params.require(:dish).permit(:name, :price, :description, :quantity, :photo, :start_time, :end_time, :date, :rating)
  end
end

app/views/dishes/_new.html.erb
<div class="p-4 rounded">
  <h1>Adicione o prato aqui</h1>
  <p>Conte-nos um pouco sobre a comida que você oferecerá em suas bolsas mágicas.</p>
  <div class="container mt-4">
    <%= simple_form_for [@restaurant, @dish] do |f| %>
      <%= f.input :name, label: "Nome", input_html: { maxlength: '22' } %>
      <%= f.input :price, label: "Preço (R$)", input_html: { min: '0', step: 'any' }  %>
      <%= f.input :description, label: "Descrição do prato", input_html: { maxlength: '47' } %>
      <%= f.label :data_de_retirada %>
      <%= f.date_field :date, min: Date.today %>
      <br>
      <%= f.label :horário_mínimo_de_retirada %>
      <%= f.time_field :start_time %>
      <br>
      <%= f.label :horário_máximo_de_retirada %>
      <%= f.time_field :end_time %>
      <br>
      <%= f.input :quantity, label: "Quantidade de pratos" %>
      <%= f.input :photo, as: :file, label: "Insira uma foto" %>
      <%= f.button :submit, "Criar prato", class:"btn btn-bg w-100"%>
    <% end %>
  </div>
</div>

app/views/dishes/_show.html.erb
<div class="row no-gutters justify-content-center rounded">
  <div class="row">
    <div class="col-12">
      <% if mobile_device == "mobile" %>
        <h1 class="card-title"><%= dish.name %></h1>
        <h1 class="card-title">
          <% if !dish.rating.nil? %>
            <% dish.rating.times do %>
              <i class="fas fa-star"></i>
            <% end %>
          <% end %>
        </h1>
      <% else %>
        <h1 class="card-title"><%= dish.name %>
          <% if !dish.rating.nil? %>
            <% dish.rating.times do %>
              <i class="fas fa-star"></i>
            <% end %>
          <% end %>
        </h1>
      <% end %>
    </div>
  </div>
  <div class="row align-items-center">
    <div class="col-12 col-lg-6 mb-3">
      <% if mobile_device == "mobile" %>
        <%= cl_image_tag dish.photo.key, height: 200, width: 250, crop: :fill, class:"rounded ml-5"%>
      <% else %>
        <%= cl_image_tag dish.photo.key, height: 300, width: 400, crop: :fill, class:"rounded mb-3"%>
      <% end %>
    </div>
    <div class="col-md-6">
      <div class="card-body">
        <h4> <%= link_to "Veja todos os pratos de #{dish.restaurant.name}", restaurant_path(dish.restaurant),  class:"card-title" %> </h4>
        <h5 class="card-title"> <%="Avaliação de #{dish.restaurant.name}:"%>
            <% dish.restaurant.rating.times do %>
              <i class="fas fa-star"></i>
            <% end %>
        </h5>
        <hr>
        <h5 class="card-text"> <%= dish.description %> </h5>
        <h5 class="card-text"><b>Preço:</b> R$ <%= dish.price %></h5>
        <hr>
        <h5 class="card-text"> <b>Retire seu pedido em:</b> <%= dish.restaurant.address %></h5>
        <h5 class="card-text"><b>Retirada entre às</b> <%= dish.start_time&.to_formatted_s(:time) %> e <%= dish.end_time&.to_formatted_s(:time) %></h5>
      </div>
      <div class="ml-3">
        <% if current_user.nil? %>
          <%= link_to "Faça seu login para reservar", new_user_session_path, class:"btn btn-flat" %>
        <% elsif dish.restaurant.user == current_user %>
          <%= link_to "Veja meus pedidos", restaurant_orders_path(dish.restaurant), class:"btn btn-flat" %>
        <% else %>
          <%= simple_form_for [dish, order] do |f| %>
            <button id="sweet-alert-demo" class="btn btn-flat">Reserve já!</button>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/dishes/edit.html.erb
<div class="container-fluid">
  <div class="row justify-content-center">
    <%= render 'restaurants/sidebar', restaurant: @restaurant %>
    <div class="card-dish mt-2 p-3 card-border-login" style="width: 50%">
      <h1>Edite o seu prato aqui:</h1>
      <%= simple_form_for @dish do |f| %>
        <%= f.input :name, label: "Nome" %>
        <%= f.input :price, label: "Preço (R$)" %>
        <%= f.input :description, label: "Descrição do prato" %>
        <%= f.label :data_de_retirada %>
        <%= f.date_field :date, min: Date.today %>
        <br>
        <%= f.label :horário_mínimo_de_retirada %>
        <%= f.time_field :start_time %>
        <br>
        <%= f.label :horário_máximo_de_retirada %>
        <%= f.time_field :end_time %>
        <br>
        <%= f.input :quantity, label: "Quantidade de pratos" %>
        <%= f.input :photo, as: :file, label: "Insira uma foto" %>
        <%= f.button :submit, "Atualizar prato", class:"btn btn-flat w-100"%>
      <% end %>
    </div>
  </div>
</div>

app/views/dishes/index.html.erb
<div class="container mt-5">
  <% if @dishes.count.positive? %>
    <h1 class="title-h1">Confira os pratos disponíveis</h1>
    <h3>Mate sua fome e ainda ajude o planeta!</h3>
  <% else %>
    <h1 class="title-h1">Oops, não temos restaurantes próximos por aqui hoje 😫</h1>
    <p class="text-center mt-5"><%= link_to "Ver outros endereços", root_path, class: "bcolor btn btn-flat" %> </p>
  <% end %>
  <div class="row justify-content-between">
    <% @dishes.each do |dish| %>
      <% if dish.quantity > 0 %>
        <div class="card mb-3 rounded col-12 col-lg-6">
          <div class="row justify-content-between flex-wrap align-items-center rounded">
            <div class="col-5 col-lg-5">
              <% if mobile_device == "mobile" %>
                <%= cl_image_tag dish.photo.key, width: 150, height: 150, crop: :fill, class:"rounded" %>
              <% else %>
                <%= cl_image_tag dish.photo.key, width: 220, height: 220, crop: :fill, class:"rounded ml-2" %>
              <% end %>
            </div>
            <div class="col-7 col-lg-7">
              <div class="card-body">
                <h4 class="card-title">
                  <%= dish.name %>
                  <h5 class="card-title">
                  <% if !dish.rating.nil? %>
                    <% dish.rating.times do %>
                      <i class="fas fa-star"></i>
                    <% end %>
                  <% end %>
                  </h5>
                </h4>
                <h5 class="card-text"><strong><%= dish.restaurant.name %></strong> </h5>
                <p class="card-text">R$ <%= dish.price %> </p>
                <p class="card-text"><%= dish.description %> </p>
                <hr>
                <% if mobile_device == "mobile" %>
                  <button type="button" class="btn btn-flat" data-toggle="modal" data-target=<%="#dish-#{dish.id}"%>>
                    Detalhes
                  </button>
                <% else %>
                  <button type="button" class="btn btn-flat" data-toggle="modal" data-target=<%="#dish-#{dish.id}"%>>
                    Veja detalhes
                  </button>
                <% end %>
                <!-- Modal -->
                <div class="modal fade rounded" id=<%="dish-#{dish.id}"%> tabindex="-1" aria-labelledby=<%="#dish-#{dish.id}Label"%> aria-hidden="true">
                  <div class="modal-dialog modal-dialog-centered modal-lg rounded">
                    <div class="modal-content p-3 rounded">
                      <%= render 'show', dish: dish, order: @order %>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/dishes/index_owner.html.erb
<div class="container-fluid mt-4">
  <div class="row justify-content-center">
    <%= render 'restaurants/sidebar', restaurant: @restaurant %>
    <div class="card-dish m-2 p-3 ml-5 card-border" style="width: 60%">
      <h1>Refeições Disponíveis</h1>
    </div>
    <div class="card-dish m-2 p-3 ml-5 card-border" style="width: 60%">
      <% @dishes.each do |dish| %>
        <% if dish.quantity > 0 %>
          <div class="row align-items-center">
            <div class="col-md-5">
              <%= cl_image_tag dish.photo.key, height: 250, width: 350, crop: :fill, class:"rounded mb-3"%>
            </div>
            <div class="col-md-7 mb-4">
              <div class="card-body">
                <h5 class="card-title"> <%= dish.name %>
                  <% if !dish.rating.nil? %>
                    <% dish.rating.times do %>
                      <i class="fas fa-star"></i>
                    <% end %>
                  <% end %>
                </h5>
                <hr>
                <h6 class="card-text"> <%= dish.description %> </h6>
                <h6 class="card-text"><b>Preço:</b> R$ <%= dish.price %></h6>
                <hr>
                <h6 class="card-text"> <b>Retire seu pedido em:</b> <%= dish.restaurant.address %></h6>
                <h6 class="card-text"><b>Retirada entre às</b> <%= dish.start_time&.to_formatted_s(:time) %> e <%= dish.end_time&.to_formatted_s(:time) %></h6>
              </div>
              <div class="ml-3 d-flex justify-content-between">
                <%= link_to "Editar", edit_dish_path(dish), class:"btn btn-flat btn-edit" %>
                <%= link_to "Excluir", dish_path(dish), method: :delete, data: { confirm: "Você tem certeza?" }, class:"btn btn-flat btn-delete" %>
              </div>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
</div>