config/routes.rb
Rails.application.routes.draw do
  #get 'profiles/show'
  devise_for :users

  resources :restaurants do
    resources :dishes, only: [:create]
    resources :orders, only: [:index]
    get "/dashboard", to: "restaurants#dashboard"
    get "/index_today", to: "orders#index_today"
    get "/index_owner", to: "dishes#index_owner"
  end

  resources :dishes, only: [:index, :edit, :update, :destroy] do
    resources :orders, only: [:create, :index]


  end
  resources :profiles, only: [:show]
  resources :orders, only: [:show, :update]
  resources :chatrooms, only: :show do
    resources :messages, only: :create
  end

  patch ":id/claim", to: "orders#claim", as: :claim
  root to: 'pages#home'
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  belongs_to :user

  validates :name, :address, :category, presence: true
  has_many :dishes, dependent: :destroy
  has_many :orders, through: :dishes
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
  has_one_attached :photo

  after_create :update_owner

  def rating
    if self.orders.empty? || self.dishes.empty? || self.dishes.pluck(:rating).nil?
      0
    else
      notas = []
      self.dishes.pluck(:rating).each do |rating|
        notas.append(rating) unless rating.nil?
      end
      notas.sum / self.dishes.count
    end
  end

  private

  def update_owner
    user.update(owner: true)
  end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: %i[show edit update destroy]
  skip_before_action :authenticate_user!, only: [:show]

  def index
    @restaurants = policy_scope(Restaurant).where(user_id: current_user)
  end

  def dashboard
    # Unique method for displaying a dashboard for each restaurant
    @restaurant = Restaurant.find(params[:restaurant_id])
    authorize @restaurant
    @dish = Dish.new
  end

  def show
    @order = Order.new
  end

  def new
    @restaurant = Restaurant.new
    authorize @restaurant
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    @restaurant.user = current_user

    authorize @restaurant

    if @restaurant.save
      redirect_to restaurant_dashboard_path(@restaurant)
    else
      render :new
    end
  end

  def edit
  end

  def update
    @restaurant.update(restaurant_params)
    redirect_to restaurant_path(@restaurant)
  end

  def destroy
    @restaurant.destroy
    redirect_to profile_path(current_user)
  end

  private

  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
    authorize @restaurant
  end

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :category, :phone, :photo)
  end
end

app/views/restaurants/_form.html.erb
<%= simple_form_for restaurant do |f| %>
  <%= f.input :name, label: "Nome do Restaurante" %>
  <%= f.input :address, label: "Endereço" %>
  <%= f.input :category, label: "Categoria", collection: ["Árabe", "Brasileira", "Chinesa", "Italiana", "Japonesa", "Lanche", "Padaria", "Pizza"]  %>
  <%= f.input :phone, label: "Telefone" %>
  <%= f.input :photo, label: "Insira uma foto", as: :file %>
  <%= f.button :submit, class:"btn btn-flat w-100" %>
<% end %>

app/views/restaurants/_info_window.html.erb
<%= link_to restaurant_path(restaurant), class:"map-link" do %>
  <h2> <%=  restaurant.name %> </h2>
<% end %>
<p><%= restaurant.address %></p>

app/views/restaurants/_sidebar.html.erb
<nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block sidebar collapse" style="width: 25%">
  <div class="position-sticky pt-3">
    <ul class="nav flex-column">
      <li class="nav-item">
        <%= link_to restaurant_dashboard_path(@restaurant), class: "nav-link" do %>
          <i class="fas fa-home"></i>
          <%="Dashboard de #{@restaurant.name}"%>
        <% end %>
      </li>
      <li class="nav-item">
        <%= link_to restaurant_orders_path(@restaurant), class: "nav-link" do %>
          <i class="fas fa-tasks"></i>
          Pedidos
        <% end %>
      </li>
      <li class="nav-item">
        <%=link_to restaurant_index_owner_path(@restaurant), class: "nav-link" do %>
          <i class="fas fa-utensils"></i>
          Refeições
        <% end %>
      </li>
      <li class="nav-item">
        <%=link_to restaurant_path(@restaurant), class: "nav-link" do %>
          <i class="fas fa-store"></i>
          <%= "Perfil de #{@restaurant.name}" %>
        <% end %>
      </li>
      <li class="nav-item">
        <%= mail_to "sobrouapp@gmail.com", class: "nav-link" do %>
          <i class="fas fa-question"></i>
          <%= "Dúvidas" %>
          <i class="fas fa-question"></i>
        <% end %>
      </li>
    </ul>
  </div>
</nav>

app/views/restaurants/dashboard.html.erb
<div class="container-fluid mt-4">
  <div class="row justify-content-center">
    <%= render 'sidebar' %>
    <div class="container">
      <div class= "row d-flex justify-content-center">
        <div class="card-dish m-3 p-3 card-border" style="width: 70%">
          <h1 style="font-family:Open Sans">Olá!</h1>
          <p style="font-family:Open Sans"> Nesta página você encontra tudo sobre os seus dados cadastrados, seus pratos disponíveis e pedidos.</p>
          <p style="font-family:Open Sans"> Obrigado por fazer parte desta revolução :) </p>
        </div>
          <div class= "row d-flex justify-content-center">
            <div class="card-dish m-3 p-3 card-border" style="width: 70%">
              <div class="row d-flex justify-content-center">
                <div class="card mx-3 p-3 card-main card-border col-12 col-lg-5 flex-column">
                  <h1 style="font-family:Open Sans">Adicione a refeição que sobrou aqui:</h1>
                  <p >Conte-nos um pouco sobre a comida que você oferecerá em suas bolsas mágicas e prepare-se para começar a economizar seu excedente de comida.</p>
                  <button type="button" class="btn btn-bg" data-toggle="modal" data-target="#exampleModal">
                    Adicione o prato
                  </button>
                  <div class="modal fade rounded" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                    <div class="modal-dialog modal-lg rounded">
                      <div class="modal-content rounded">
                        <%= render 'dishes/new' %>
                      </div>
                    </div>
                  </div>
                </div>
                <div class="card mx-3 p-3 card-main card-border col-12 col-lg-5 flex-column">
                  <h1 style="font-family:Open Sans">Acompanhe os pedidos de hoje:</h1>
                  <p> Aqui você pode acompanhar quais pedidos você têm em andamento, qual é o horário de coleta, tipo de refeição e o nome do cliente que irá recolher.</p>
                  <%= link_to "Seus pedidos", restaurant_index_today_path(@restaurant), class:"btn btn-bg mt-auto"%>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/restaurants/edit.html.erb
<div class="container mt-4">
  <h1>Edite seu restaurante:</h1>
  <%= render 'form', restaurant: @restaurant %>
</div>

app/views/restaurants/index.html.erb
<div class="container mt-4">
  <h1 class="my-3">Gerencie seus restaurantes:</h1>
  <% @restaurants.each do |restaurant| %>
    <div class="card-product my-4 row">
      <div class="col-2">
        <%= cl_image_tag restaurant.photo.key, height: 300, width: 300, crop: :fill%>
      </div>
      <div class="card-product-infos col-6">
        <h3><%= restaurant.name %></h3>
        <h5><strong>Endereço: </strong><%= restaurant.address %> </h5>
      </div>
      <div class="col-4">
        <%= link_to "Dashboard de #{restaurant.name}", restaurant_dashboard_path(restaurant), class:"btn-flat" %>
      </div>
    </div>
  <% end %>
</div>

app/views/restaurants/new.html.erb
<div class="banner-g" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url('https://blog.cgtsolucoes.com/wp-content/uploads/2018/08/230935-conheca-x-negocios-lucrativos-com-baixo-investimento.jpg');">
  <div class="container mt-4">
    <div class="card-form p-4 card-border">
      <h1 class="mb-3">Cadastre o seu restaurante:</h1>
      <p>Vamos juntos combater o despedício de comida e, ao mesmo tempo, gerar mais receita para o seu negócio!</p>
      <%= render 'form', restaurant: @restaurant  %>
    </div>
  </div>
</div>

app/views/restaurants/show.html.erb
<div class="container mt-4">
  <div class="row justify-content-center">
    <% if !current_user.nil? && @restaurant.user == current_user %>
      <%= render 'sidebar' %>
    <% end %>
    <div class="col-10">
      <div class="row">
        <div class="d-flex justify-content-between">
          <div class="col-9">
            <div class="d-flex justify-content-between">
              <div class="col-12">
                <h1><strong>Detalhes do <%= @restaurant.name %></strong></h1>
                <h2>
                  <% @restaurant.rating.times do %>
                    <i class="fas fa-star"></i>
                  <% end %>
                </h2>
                <div class="d-flex space-between">
                  <div>
                    <h2 class="mb-4">Veja abaixo: </h2>
                    <h4><strong>Nome: </strong><%= @restaurant.name %> </h4>
                    <h4><strong>Endereço: </strong><%= @restaurant.address %> </h4>
                    <h4><strong>Categoria: </strong><%= @restaurant.category %> </h4>
                    <h4><strong>Telefone: </strong><%= @restaurant.phone %> </h4>
                    <h4><strong>Refeições salvas: </strong><%= @restaurant.orders.empty? ? "0" : @restaurant.orders.size%> </h4>
                    <h4><strong>Kgs de comida salvos: </strong><%= @restaurant.orders.size * 0.46.round(1) %> Kg salvos </h4>
                  </div>
                  <div class="col-3 mt-5">
                  <%= cl_image_tag @restaurant.photo.key, height: 200, width: 200, crop: :fill %>
                  </div>
                </div>
              </div>
              <% if !current_user.nil? && @restaurant.user == current_user %>
                <div class="col-8">
                  <div class="mt-1">
                    <%= link_to "Editar restaurante", edit_restaurant_path(@restaurant), class:"btn btn-flat" %>
                  </div>
                  <div class="mt-4">
                    <%= link_to "Excluir restaurante", restaurant_path(@restaurant), method: :delete, data: { confirm: "Você tem certeza que deseja excluir #{@restaurant.name}?" }, class:"btn btn-flat" %>
                  </div>
                </div>
              <% end %>
            </div>
          </div>
        </div>
      </div>


      <% @restaurant.dishes.each do |dish| %>
        <div class="card-product my-4 row w-100">
          <div class="col-2">
            <%= cl_image_tag dish.photo.key, crop: :fill %>
          </div>
          <div class="card-product-infos col-7">
            <h2 class="card-title"><%= dish.name %>
              <% if dish.rating.present? %>
                <% dish.rating.times do %>
                  <i class="fas fa-star"></i>
                <% end %>
              <% end %>
            </h2>
            <p>R$ <%= dish.price %> </p>
            <p> <%= dish.description %> </p>
          </div>
          <% if !current_user.nil? && @restaurant.user == current_user %>
            <div class="col-3">
              <%= link_to "Editar prato", edit_dish_path(dish), class:"btn btn-flat" %>
            </div>
            <% else %>
            <div class="col-3">
              <!-- Button trigger modal -->
                <button type="button" class="btn btn-flat" data-toggle="modal" data-target=<%="#dish-#{dish.id}"%>>
                  Veja detalhes
                </button>

                <!-- Modal -->
                <div class="modal fade rounded" id=<%="dish-#{dish.id}"%> tabindex="-1" aria-labelledby=<%="#dish-#{dish.id}Label"%> aria-hidden="true">
                  <div class="modal-dialog modal-dialog-centered modal-lg rounded">
                    <div class="modal-content p-3 rounded">
                      <%= render 'dishes/show', dish: dish, order: @order %>
                    </div>
                  </div>
                </div>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</div>